build:
  guard/standalone:
    kit: deno.bundle
  guard/embedded:
    kit: deno.bundle
  fake-service:
    kit: deno.bundle
  judge/server:
    kit: deno.bundle
  policy/builder:
    kit: deno.bundle
  audit/server:
    kit: deno.bundle
  console/server:
    kit: deno.bundle
  console/web:
    kit: react
